project: 
  type: website
  
website: 
  page-navigation: true
  title: "Flounder Research for Actionable Management and Engagement" 
  site-url: "https://thefaylab.github.io/frame" 
  repo-url: https://github.com/thefaylab/frame 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By TheFayLab, 2025; Openscapes, 2024"
    
  sidebar:
    logo: "images/frame-temp-logo.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://thefaylab.github.io/frame
        text: "FRAME"
      - icon: github
        href: https://github.com/thefaylab/frame
        text: "website"
      
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: About
      - href: team.qmd
        text: Team
      - href: contact.qmd
        text: Contact Us

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
