---
title: "Flounder Research for Actionable Management and Engagement"
---

## Welcome {#welcome}

Welcome to the project website for [NSF Award \# 2408987](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2408987)

*DISES: Dynamics of socio-environmental factors driving resilience of coastal fisheries: integrating feedbacks between livelihoods, human behavior, climate, and fish ecology*

Principal Investigator: Dr. Holly Kindsvater, Virginia Tech

### Project overview

The recreational and commercial fisheries for summer flounder (*Paralichthys dentatus*) produce hundreds of millions of dollars in revenue to coastal economies in the mid-Atlantic and Northeast US. Recent changes in geographic distribution and dramatic fluctuations in the productivity of summer flounder, as a result of climate change and intense fishing pressure, have directly affected charter-boat captains, commercial seafood fishers, processors, dealers, and recreational fishers. Little is known about the behavioral and economic responses of policy makers and fishers to fluctuations in abundance and the total allowable catch. There has been a general movement in flounder abundance from south to north along the Atlantic coast in recent years, and this migration provides a rich opportunity to determine in detail the feedbacks between climate, fish ecology, policy regulations, and fishers who rely on summer flounder for their livelihoods, nutrition, and recreation This research will help to develop recommendations for policy solutions that meet multiple sustainability benchmarks, such as ecological sustainability, nutritional provisioning, and economic sustainability.

This project will address the interactions between fish abundance, limits on allowable catch, and fish ecology from four perspectives. (1) Social scientists will use panel surveys and in-person interviews, working with community partners, to identify the fishery?s ecosystem services, its influence on human well-being, and how these have been altered as waters have warmed and the population distribution has changed. A key goal is to determine how recreational anglers have responded to recent management actions put in place in response to the changes in flounder ecology. Attitudes toward the fairness of management and level of compliance could potentially reveal aspects of angler behavior that are currently unknown to management agencies and could explain recent struggles to manage the resource effectively. (2) Economists will use analysis of contributions of the commercial flounder fishery to coastal economies to understand the consequences of changes in management. Instability in the annual flounder catch limit due to changes in flounder abundance, as well as a mismatch between historic policy and the current distribution of flounder, have changed the economic contributions of the resource. This research will better illuminate how policymakers can manage the fishery to promote resilience in both human and ecological communities. (3) Climate scientists will determine the mechanisms linking climate and oceanographic variables to population dynamics of summer flounder using existing data on relative flounder abundance and ocean conditions. This research will investigate how variable oceanic conditions determine annual variability of juvenile flounder numbers, which will reveal how climate-driven changes in oceanography affect population ecology. (4) An advisory committee with representatives from state and federal entities involved in coastal fisheries will meet each year to synthesize the social and economic data with the results from the climate analyses. These meetings will lead to predictions of the responses of this multi-faceted system under future scenarios of climate change.
